### ISSUE TITLE
Get Gas command: one year timeout message

### ISSUE THREAD

**Issue by soundboy3113** [makkinga/dfk-tipbot#4]
A number of users have been reporting receiving an error message from Kessing, when using the /get-gas command, that they need to wait for their timeout period to end in a year.  See image below for one example:

![image](https://user-images.githubusercontent.com/67245126/158004070-9115c641-5e06-4dea-b57e-fff6d1319bab.png)

**Comment by makkinga** [comment]
Hi there Soundboy,

This is not an error. The `/get-gas` is meant to help users out on the initial onboarding. Gas for tipping should be provided by the users themselves. I know more people were confused about the message, so it will be updated to a more descriptive response today.
